name: atsc528
channels:
  - defaults
dependencies:
  - python=3.10
  - conda-forge::numpy
  - conda-forge::matplotlib
  - conda-forge::cartopy
  - conda-forge::notebook
  - conda-forge::nb_conda_kernels
  - conda-forge::jupyterlab
  - conda-forge::jupyter_contrib_nbextensions
